SimpleSocialNetwork/SimpleSocialNetwork/Controllers/MessagingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using AutoMapper;
using SimpleSocialNetwork.Bll.DTO;
using SimpleSocialNetwork.Bll.Interfaces;
using SimpleSocialNetwork.Models;
using SimpleSocialNetwork.Util;

namespace SimpleSocialNetwork.Controllers
{
    public class MessagingController : Controller
    {
        private readonly IUserService _userService;
        private readonly ITalkService _talkService;
        private readonly IMessageService _messageService;
        private readonly IMapper _mapper;

        public MessagingController(IUserService userService, ITalkService talkService, IMessageService messageService)
        {
            _userService = userService;
            _talkService = talkService;
            _messageService = messageService;
            _mapper = AutoMapperConfigWeb.Mapper;
        }

        // GET: Messaging
        [HttpGet]
        public ActionResult Talk()
        {
            //todo:rewright for using identity
            var user = _userService.GetAll().First(x => x.Id == 1);
            //var talk = _talkService.GetAll().First(x => x.Id == 1);
            //user.Talks = new List<TalkDTO>(){talk};
            return View(_mapper.Map<UserDTO,UserViewModel>(user));
        }

        public ActionResult ShowMessage(int id)
        {
            var user = _userService.GetAll().First(x => x.Id == 1);
            var userVM = _mapper.Map<UserDTO, UserViewModel>(user);

            var messageView = new ShowMessageViewModel()
            {
                FromWho = userVM.Talks.First(x=>x.Id == id).FromWho,
                ToWho = userVM.Talks.First(x=>x.Id == id).ToWho,
                Messages = userVM.Talks.First(x=>x.Id == id).Messages,
                TalkID = id
            };
            return PartialView(messageView);
        }

        [HttpPost]
        public ActionResult AddNewMessage(ShowMessageViewModel smvm)
        {
            //todo:rewright for using identity
            var user = _userService.Get(1);

            var talk = _talkService.GetAll().First(x => x.Id == smvm.TalkID);

            var changes = new MessageDTO()
            {
                Id = talk.Messages.Count+1,
                User = user,
                Text = smvm.Text,
                IsRead = false,
                Talk = talk,
                DateTime = DateTime.Now
            };
            
            _messageService.Add(changes);

            return RedirectToAction("ShowMessage",new RouteValueDictionary(new {id = talk.Id}));
        }
    }
}

SimpleSocialNetwork/SimpleSocialNetwork/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @*<link rel="stylesheet" href="~/Content/bootstrap.min.css">*@
    <link rel="stylesheet" href="~/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="~/Content/Login-Form-Clean.css">
    <link rel="stylesheet" href="~/Content/Navigation-with-Button.css">
    <link rel="stylesheet" href="~/Content/Navigation-with-Search.css">
    <link rel="stylesheet" href="~/Content/Site.css">

</head>
<body class="pt-0">
    <div class="navbar navbar-dark navbar-expand-md navigation-clean-button">
        <div class="container">
            <a class="navbar-brand">Simple Social Network</a>
            <button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse"
                 id="navcol-1">
                <ul class="nav navbar-nav mr-auto">
                    <li class="nav-item m-1 p-1" role="presentation">
                        @Html.ActionLink("Profile", "UserProfile", "Profile")
                    </li>
                    <li class="nav-item m-1 p-1" role="presentation">
                        @Html.ActionLink("Friends", "Index", "Friends")
                    </li>
                    <li class="nav-item m-1 p-1" role="presentation">
                        @Html.ActionLink("Messages", "Talk", "Messaging")
                    </li>
                </ul>
                
                <span class="d-flex flex-column">
                    @Html.Partial("_LoginPartial")
                </span>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>